In [2]:
import numpy as np

## Numpy
Numpy is the python library you will use to manipulate vectors, matrices, and densors. In Numpys these mathematical objects are all implemented as "arrays". This tutorial will show you how to create and manipulate arrays

Other note: there are many great python tutorials in notebook format. For example, the current tutorial borrows heavily from:

https://github.com/kuleshov/cs228-material/blob/master/tutorials/python/cs228-python-tutorial.ipynb



### Arrays
"A numpy array is a grid of values, all of the same type, indezed by a non-negative integers."

Here we implement a simple vector with 3 elements as an array

In [3]:
x = np.array([1,2,3])
print x

[1 2 3]


Like all things in python, x is an object with associated attributes and methods.

One important attribute is array "shape"

In [4]:
print x.shape

(3,)


the shape attribute is a tuple of numbers giving the size of each dimension. One important thing to note is that numpy distinguishes between 1D arrays like x, which is neither a row or column vector, and 2D arrays with shape tuples that look like (1,D), for example:

In [5]:
y = np.array([1,2,3],ndmin=2)
print 'shape of y: %s' % (y.shape,)
print 'shape of x: %s' % (x.shape,)

shape of y: (1, 3)
shape of x: (3,)


The key difference is the "ndmin" argument, which disambiguates by allowing you to specify the minimum number of dimensions. There's an attribute for number of dimensions too

In [6]:
print "number of x dimensions: %d" %x.ndim
print "number of y dimensions: %d" %y.ndim

number of x dimensions: 1
number of y dimensions: 2


We can create arrays with more dimensions by passing lists of lists

In [8]:
z = np.array([[1,2,3], [4,5,6], [7,8,9]])
print z


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
z * 10


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

#### Exercise:
Create a 3D array with shape tuple (2,2,2) using a nested list construction

In [7]:
###your code here

numpy provides all sorts of ways to initialize newly create arrays

In [8]:
a = np.zeros((1,2)) 
print a

[[ 0.  0.]]


the (1,2) tuple argument passed to "zeros" determines the array's shape

In [9]:
b = np.ones((2,2,2))
print b

[[[ 1.  1.]
  [ 1.  1.]]

 [[ 1.  1.]
  [ 1.  1.]]]


In [10]:
c = np.full((2,2),7)
print c

[[7 7]
 [7 7]]


In [11]:
d = np.eye(6)
print d

[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]


In [ ]:
f = np.random.random((3,3)) ##random values between 0,1
print f

#### Exercise
Create a (3,3) array of numbers in the range (1,2)

In [ ]:
##your code here

### Array shape manipulation
Sometimes you will want to change the shape of your array. For example, suppose we have a 16 x 16 image and we want to turn into in a flat array.

In [ ]:
img = np.random.random((16,16))
print img.shape


In [ ]:
flat_img = img.ravel()
print flat_img.shape

Now, let's retain the image format


In [ ]:
img2 = flat_img.reshape((16,16))
print img2.shape

Conveniently, the transpose operation is built-in into each array

In [ ]:
x = np.ones((10,5))
print x.shape
y = x.T
print y.shape

Finally, it is sometimes useful to add "dummy" axes to an array for purposes of broadcasting (below). For this we can use the "np.newaxis" notation. In this example, we insert a new dimension into a 2D array.

In [ ]:
x = np.ones((10,10))
print x.shape
y = x[:, np.newaxis, :]
print y.shape

#### Exercise 
Construct a 9 x 16 x 16 "movie" of random, 16x16 images. Reformat the movie into a flat 3x3 "montage" of the individual frames.

In [ ]:
### your code here

### Array indexing
To retrieve specific elements on an array, we can use the bracket notation []. This is called "slicing"

In [ ]:
z = np.array([[1,2,3,10], [4,5,6,11], [7,8,9,12]])
print z

In [ ]:
##equivalent ways to get the first row
print z[0]
print z[0,:]



In [ ]:
##get first column
print z[:,0]

In [ ]:
##get the first element
z[0,0]

In [ ]:
##get the last element of first row
z[0,-1]

In [ ]:
##get everything but the last element of the first row
z[0,:-1]

In [ ]:
##access the second row, returning a 1D array
print z[1,:], z[1,:].shape

In [ ]:
##access the second rown, returning a 2D array
print z[1:2,:], z[1:2,:].shape

In [ ]:
##submatrix in the bottom corner
print z[1:,-2:]


Suppose we have a stack of images stored as a 3D tensor (N, P, P), where N = number of images, P = pixel resolution of images. We can select images by slicing the first dimension only

In [ ]:
N,P = 10,16
g = np.random.random((N,P,P))
print g.shape
print g[:3].shape

Integer indexing: instead of slicing, pass lists (or tuples) of indices

In [ ]:
##access every other element of first row
print z[0,[0,2,]]
##or
print z[0,[1,-1]]

In [ ]:
##access lists of individual elements specified by (i,j) pairs: for example, the diagonal
print z[[0,1,2], [0,1,2]]
##is just like
print np.array([z[0,0], z[1,1], z[2,2]])

#### Exercise
Create two lists "row_dx" and "col_dx" such that z[row_dx, col_dx] returns elements at the four corners of the matrix z

In [ ]:
###your code here

Boolean indexing: pass an array or list of True/False elements. Must match shape of original array or errors/weird things can happen.

In [ ]:
##convert array to booleans
z > 5

In [ ]:
##to get a 1D array of all the elements marked "true" we can just go
print z[z>5]

### Array assignment
Here's something you need to know: if you assign an indexed array element to a new variable, modifications to that new variable will modify the original indexed array!

In [ ]:
z = np.array([[1,2,3,10], [4,5,6,11], [7,8,9,12]])
x = z[0,:]
print x
print x[0]

In [ ]:
x[0] = 0
print x[0]
print z[0,0]

...NOTE: if we reference only a single element of z, changes to the referencing variable no longer modify original array!!

In [ ]:
x = z[0,0]  ##x is now a simple scalar
print x, x.shape
##changes to x don't propagate back to z
x += 10
print x
print z[0,0]

### Math

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print x + y
print np.add(x, y)

In [ ]:
# Elementwise difference; both produce the array
print x - y
print np.subtract(x, y)

In [ ]:
# Elementwise product; both produce the array
print x * y
print np.multiply(x, y)

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print x / y
print np.divide(x, y)

Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum


In [ ]:
x = np.array([[1,2],[3,4]])

print np.sum(x)  # Compute sum of all elements; prints "10"
print np.sum(x, axis=0)  # Compute sum of each column; prints "[4 6]"
print np.sum(x, axis=1)  # Compute sum of each row; prints "[3 7]"

### Broadcasting
This is an involved subject, but note that if we want to add the same row to every row of a matrix, we can do this


In [ ]:
##add 
x = np.random.randn(2,100000)
print x.shape
z = np.ones((2,1))
print 'plus'
print z.shape
y = x+z
print 'makes'
print y.shape
print '\n'

##notice we've changed the mean
print 'mean of cols in x: %s' %(np.mean(x,axis=1),)
print 'mean of cols in y: %s' %(np.mean(y,axis=1),)

Now try the same thing, but with a subtle change: the added vector "z" is now 1D.


In [ ]:
##add 
x = np.random.randn(2,100000)
print x.shape
z = np.ones((2))
print 'plus'
print z.shape
print 'makes'
y = x+z
print y.shape
print '\n'

##### This is why it's important to observe the difference between arrays with shape (1,D) and (D,) !!!!

### Plotting

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

# Plot the points using matplotlib
plt.plot(x, y, 'r')  ##'r' makes it red

In [ ]:
##A scatter plot
x = np.random.random((1,18))
y = np.random.random((1,18))
plt.scatter(x,y)
plt.plot(np.linspace(0,1,), np.linspace(0,1)) ##default color is blue

In [ ]:
##A histogram
plt.subplot(3,1,1)
x = np.random.randn(100)
_=plt.hist(x,bins=100)
plt.subplot(3,1,2)
x = np.random.randn(1000)
_=plt.hist(x,bins=100)
plt.subplot(3,1,3)
x = np.random.randn(10000)
_=plt.hist(x,bins=100)

#### Exercise
Generate some fake data: two clouds of points in the plain, one centered at (-2,2) and another centered at (2,-2).

Make a 3-panel plot with the following:
     1. A scatterplot with the different clouds of points in two different colors
     2. A histogram of the data distribution along the x-axis
     3. A histogram of the data distribution along the y-axis



In [ ]:
###your code here